
package arcanoid;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.TextField;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;


public class JBoxFrame extends javax.swing.JFrame {

    private static final int STEP=7;
    private static int dx, dy;
    private ThreadMove thread;
   public static int jLineX, jLineY;
    public int i=0;
  
    
    /**
     * Creates new form JBoxFrame
     */
    public JBoxFrame() {
        initComponents();
        dx=dy=1;// right, down
      // jPanel2.setLayout(null);//!!!
        //jBox.setLayout(null);
      // jLine.setLayout(null);
       jBox.setLocation(new Random().nextInt(jPanel2.getWidth()-jBox.getWidth()), 
                   new Random().nextInt(jPanel2.getHeight()-jBox.getHeight()));
       
       jLine.setLocation(jPanel2.getWidth(), jLine.getWidth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jStartBtn = new javax.swing.JButton();
        jStopBtn = new javax.swing.JButton();
        jExitBtn = new javax.swing.JButton();
        jText = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jBox = new javax.swing.JPanel();
        jLine = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 255)));

        jStartBtn.setText("Start/Faster");
        jStartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStartMove(evt);
            }
        });
        jStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartBtnActionPerformed(evt);
            }
        });

        jStopBtn.setText("Stop");
        jStopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStopMove(evt);
            }
        });

        jExitBtn.setText("Exit");
        jExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit(evt);
            }
        });

        jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStopBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jExitBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartBtn)
                    .addComponent(jStopBtn)
                    .addComponent(jExitBtn)
                    .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });

        jBox.setBackground(new java.awt.Color(153, 51, 255));

        javax.swing.GroupLayout jBoxLayout = new javax.swing.GroupLayout(jBox);
        jBox.setLayout(jBoxLayout);
        jBoxLayout.setHorizontalGroup(
            jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jBoxLayout.setVerticalGroup(
            jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLine.setBackground(new java.awt.Color(51, 0, 51));
        jLine.setBorder(new javax.swing.border.MatteBorder(null));
        jLine.setForeground(java.awt.Color.white);
        jLine.setToolTipText("drag and click");
        jLine.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLineMouseDragged(evt);
            }
        });
        jLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLineMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jLineLayout = new javax.swing.GroupLayout(jLine);
        jLine.setLayout(jLineLayout);
        jLineLayout.setHorizontalGroup(
            jLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jLineLayout.setVerticalGroup(
            jLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE)
                .addComponent(jLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartMove(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStartMove
        // TODO add your handling code here:
   thread= new ThreadMove(50, this);// создаем поток
        thread.start(); 
    }//GEN-LAST:event_jStartMove

    private void jStopMove(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStopMove
        // TODO add your handling code here: 
         thread.stop();
    }//GEN-LAST:event_jStopMove

    private void jExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit
        // TODO add your handling code here:
        this.dispose();//удаление окна
    }//GEN-LAST:event_jExit

    private void jLineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLineMousePressed
        // TODO add your handling code here:
        //Point j= jLine.getLocation();
        //Point p=jBox.getLocation(); 
        
      //if((p.y>= (jLine.getHeight()-jBox.getHeight()))) dy=-dy;
        jLineX=evt.getXOnScreen()-jLine.getX();
        jLineY=evt.getYOnScreen()-jLine.getY();
     
  // if((p.x>= (jLine.getWidth()-jBox.getWidth()))) dx=-dx;
        // jLine.setLocation(jPanel2.getWidth()-jLine.getWidth(), jPanel2.getWidth()-jLine.getWidth()) ;
        // jLine.setLocation(evt.getXOnScreen()-jLineX, evt.getYOnScreen()-jLineY);
        
    }//GEN-LAST:event_jLineMousePressed

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentResized

    private void jStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStartBtnActionPerformed

    private void jLineMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLineMouseDragged
        // TODO add your handling code here:
        //        if((j.x>= (jPanel2.getWidth()-jLine.getWidth()))) lx=-lx;      //отражение право лево
        Point j= jLine.getLocation();
        //jLine.setLocation(jPanel2.getWidth()-jLine.getWidth(), jPanel2.getWidth()-jLine.getWidth()) ;
        if ((j.x<=0)||(j.x>=(jPanel2.getWidth()-jLine.getWidth()))) jLineX=-jLineX ;
        //  if ((j.y>=(jLine.getHeight()-jBox.getHeight()))) dy=-dy;
        jLine.setLocation(evt.getXOnScreen()-jLineX, jLine.getY()-jPanel2.getY());
    
    }//GEN-LAST:event_jLineMouseDragged

    private void jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActionPerformed


    public void moveBox(){
        Point p= jBox.getLocation();//узнали где кубик
        Point j= jLine.getLocation();
        //кубик отражаетя от границ экрана
       
       
        if((p.x <=0)||(p.x>= (jPanel2.getWidth()-jBox.getWidth()))) dx=-dx;  //отражение право лево
        if((p.y<=0)||(p.y>= (jPanel2.getHeight()-jBox.getHeight()))) dy=-dy;//отражение верх низ
  
        p.move(p.x +dx*STEP, p.y +dy*STEP);//передвигаем
        jBox.setLocation(p);
         
         if ((j.x>(p.x-jLine.getWidth())) && (j.x <(p.x+jBox.getWidth()))
        && (j.y> (p.y-jLine.getHeight())) && (j.y< (p.y+jBox.getHeight())))
        {
            
            jText.setText(" " + i);
           i++;

            dx=-dx;
            dy=-dy;
  
        }
 
         
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JBoxFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBox;
    private javax.swing.JButton jExitBtn;
    private javax.swing.JPanel jLine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jStartBtn;
    private javax.swing.JButton jStopBtn;
    private javax.swing.JFormattedTextField jText;
    // End of variables declaration//GEN-END:variables
}
